# Generated by Django 3.2.10 on 2021-12-30 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogauthor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.date(2021, 12, 30)),
        ),
    ]
